### ISSUE TITLE
Feature Request: Events when Utterance has started/ended

### ISSUE THREAD

**Issue by jgilm** [jsakamoto/Toolbelt.Blazor.SpeechSynthesis#5]
It would be nice to get an event when an Utterance has started or ended.
In addition, it would be nice to know when the `SpeechSynthesis.Speaking` property has changed.

**Comment by jsakamoto** [comment]
@jgilm Thank you for proposal!

This library already had been exposed to those events via `SpeechSynthesisUtterance` at first release. 

However, as you know, this design architecture is not convenient especially using the quick speech method. (There is no chance to grab the events due to `SpeechSynthesisUtterance` object is created inside the ``SpeechSynthesis` service in this case.)

So I improved this library according to your proposal.
I published the new version of this library ver.8.1 just now.

- https://www.nuget.org/packages/Toolbelt.Blazor.SpeechSynthesis/8.1.0

This version's `SpeechSynthesis` service now relay and expose utterance events.
For more detail, please see also sample code bellow.

- https://github.com/jsakamoto/Toolbelt.Blazor.SpeechSynthesis/blob/master/SampleSites/SampleSite.Components/App.razor#L85

Please try it out. :)

By the way, exposing the event that occurs when SpeechSynthesis.Speaking property has changed is still hard due to those events not provided by Speech Synthesis API on the web browser.
I appreciate the understanding.

**Comment by jgilm** [comment]
I finally got time to test the update. Works very well! Thanks so much for the quick response on this feature request.
